### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by chrisroat** [abria/TeraStitcher#83]
I have run terastitcher 1.11.11, and also compiled at HEAD, with --fixed_tiling to generated tiff stacks, but some data seems to be missing:
- a cross-shape of data is all zeros
- there is a row of x data missing altogether (the tiff files for a slice is not produced)

Looking at the data itself, there is a missing swath of x starting at 1024 pixels from the left edge, and of y starting 1536 from the top.  The 512x512 tiff files simply have a chunk of data set to zeros when I look inside them (The data in the image has cropped the missing x-data from point 2 above):

![image](https://user-images.githubusercontent.com/1053153/110347930-f59ede80-7fe5-11eb-9334-73b074854cd8.png)

The solution to the stitching looks very reasonable and should produce an image of the expected size (3617x3613).  The relevant xml files are included in [tstitch_missing_data.zip](https://github.com/abria/TeraStitcher/files/6102691/tstitch_missing_data.zip)

The command I then use to do the conversion, which is converting from input tiffs that are 1024x1024:

```bash
mpirun -n 10 --allow-run-as-root python /usr/local/bin/paraconverter.py "--sfmt=TIFF (unstitched, 3D)" "--dfmt=TIFF (tiled, 4D)" --fixed_tiling -s=/workdir/stitched_tiff/xml_import.xml -d=/workdir/stitched_tiff --height=512 --width=512 --depth=256
```

The output stacks have a x-location jump from 3070 to 9220, which is the missing files -- there are only 6 files of 512 and a final file of 29 pixels: there is a whole file of size 512 that is missing.  (This is in addition to some of the tiff files having zeros and causing the cross shaped pattern in the image.

File list:
```bash
$ ls /workdir/stitched_tiff/RES\(3617x3613x251\)/CH_0/*/*/*tif
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/000020/000020_000000/000020_000000_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/000020/000020_003070/000020_003070_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/000020/000020_009220/000020_009220_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/000020/000020_012290/000020_012290_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/000020/000020_015360/000020_015360_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/000020/000020_018430/000020_018430_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/000020/000020_021500/000020_021500_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/0-3050/0-3050_000000/0-3050_000000_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/0-3050/0-3050_003070/0-3050_003070_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/0-3050/0-3050_009220/0-3050_009220_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/0-3050/0-3050_012290/0-3050_012290_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/0-3050/0-3050_015360/0-3050_015360_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/0-3050/0-3050_018430/0-3050_018430_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/0-3050/0-3050_021500/0-3050_021500_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/0-6130/0-6130_000000/0-6130_000000_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/0-6130/0-6130_003070/0-6130_003070_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/0-6130/0-6130_009220/0-6130_009220_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/0-6130/0-6130_012290/0-6130_012290_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/0-6130/0-6130_015360/0-6130_015360_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/0-6130/0-6130_018430/0-6130_018430_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/0-6130/0-6130_021500/0-6130_021500_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/0-9200/0-9200_000000/0-9200_000000_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/0-9200/0-9200_003070/0-9200_003070_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/0-9200/0-9200_009220/0-9200_009220_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/0-9200/0-9200_012290/0-9200_012290_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/0-9200/0-9200_015360/0-9200_015360_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/0-9200/0-9200_018430/0-9200_018430_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/0-9200/0-9200_021500/0-9200_021500_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/-12270/-12270_000000/-12270_000000_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/-12270/-12270_003070/-12270_003070_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/-12270/-12270_009220/-12270_009220_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/-12270/-12270_012290/-12270_012290_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/-12270/-12270_015360/-12270_015360_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/-12270/-12270_018430/-12270_018430_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/-12270/-12270_021500/-12270_021500_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/-15340/-15340_000000/-15340_000000_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/-15340/-15340_003070/-15340_003070_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/-15340/-15340_009220/-15340_009220_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/-15340/-15340_012290/-15340_012290_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/-15340/-15340_015360/-15340_015360_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/-15340/-15340_018430/-15340_018430_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/-15340/-15340_021500/-15340_021500_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/-18410/-18410_000000/-18410_000000_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/-18410/-18410_003070/-18410_003070_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/-18410/-18410_009220/-18410_009220_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/-18410/-18410_012290/-18410_012290_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/-18410/-18410_015360/-18410_015360_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/-18410/-18410_018430/-18410_018430_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/-18410/-18410_021500/-18410_021500_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/-21490/-21490_000000/-21490_000000_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/-21490/-21490_003070/-21490_003070_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/-21490/-21490_009220/-21490_009220_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/-21490/-21490_012290/-21490_012290_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/-21490/-21490_015360/-21490_015360_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/-21490/-21490_018430/-21490_018430_000000.tif'
'/workdir/stitched_tiff/RES(3617x3613x251)/CH_0/-21490/-21490_021500/-21490_021500_000000.tif'
```

**Comment by chrisroat** [comment]
I see many of the following messages in the logs.  I'm trying to run with fewer cores so I can disentangle where they are coming from.

```
in VolumeConverter::generateTilesVaa3DRawMC(path = "/workdir/stitched_tiff", resolutions = 1000000000, block_height = 512, block_width = 512, block_depth = 256, method = 1, show_progress_bar = true, saved_img_format = Tiff3D, saved_img_depth = 16, frame_dir = "")
```

```
munmap_chunk(): invalid pointer
```

```
**** WARNING (source: "IconImageManager::real32* UnstitchedVolume::internal_loadSubvolume_to_real32(int&, int&, int&, int&, int&, int&, int, int, int, int, int, int)") ****
    |=> "V top offset negative: set to 0"
```


```
Aborted (core dumped)
```

**Comment by chrisroat** [comment]
With my dataset, it seems that using 5 cores or less avoids the invalid pointer / core dump issue.

**Comment by chrisroat** [comment]
I created a debug build and loaded a dumped core.  The stack trace is below, where the deletion of the `buf` pointer is causing an issue.  From the debugger I see that this is happening for the first loop through channels (c=1).

 The relevant lines in malloc.c that are catching there error:

```
  size = chunksize (p);  
  ...
  if (__builtin_expect ((uintptr_t) p > (uintptr_t) -size, 0)                                                                                             
      || __builtin_expect (misaligned_chunk (p), 0))                                                                                                      
```

```
#4  0x00007f09e5715cac in _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:4173
4173        malloc_printerr ("free(): invalid pointer");
#5  0x0000563517c76dba in UnstitchedVolume::loadSubvolume_to_UINT8 (this=0x563519df97f0, V0=0, V1=512, H0=1024, H1=1536, D0=0, D1=64, 
    channels=0x7ffc840c5338, ret_type=0) at /home/croat/TeraStitcher/src/imagemanager/UnstitchedVolume.cpp:1159
1159                                            delete []buf;
#6  0x0000563517be93c0 in VolumeConverter::generateTilesVaa3DRawMC (this=0x7ffc840c5300, output_path="/workdir/stitched_tiff", ch_dir="", 
    resolutions=0x7ffc840c57c8, block_height=512, block_width=512, block_depth=256, method=1, isotropic=false, show_progress_bar=false, 
    saved_img_format=0x563517da05f5 "Tiff3D", saved_img_depth=16, frame_dir="", par_mode=true, fixed_tiling=true)
    at /home/croat/TeraStitcher/src/utils/volumeconverter/VolumeConverter.cpp:3648
3648                ubuffer[0] = volume->loadSubvolume_to_UINT8(V0,V1,H0,H1,(int)z,(z+z_max_res <= D1) ? (int)(z+z_max_res) : D1,&channels,iim::NATIVE_RTYPE);
#7  0x0000563517bd3b1d in vcDriver (vPtr=0x0, src_root_dir="/workdir/stitched_tiff/xml_import.xml", dst_root_dir="/workdir/stitched_tiff", 
    src_format="TIFF (unstitched, 3D)", dst_format="TIFF (tiled, 4D)", img_depth=0, resolutions=0x7ffc840c57c8, chanlist="", ch_dir="", mdata_fname="", 
    slice_depth=256, slice_height=512, slice_width=512, downsamplingFactor=1, halving_method=1, libtiff_rowsPerStrip=1, libtiff_uncompressed=false, 
    libtiff_bigtiff=false, show_progress_bar=true, isotropic=false, V0=0, V1=512, H0=1024, H1=1536, D0=0, D1=251, timeseries=false, makeDirs=false, 
    metaData=false, parallel=true, fixed_tiling=true, outFmt="", nbits=0) at /home/croat/TeraStitcher/src/utils/volumeconverter/VolumeConverter.cpp:335
335                                     vc.generateTilesVaa3DRawMC(dst_root_dir.c_str(),ch_dir,resolutions,
#8  0x0000563517bcf293 in main (argc=17, argv=0x7ffc840c59c8) at /home/croat/TeraStitcher/src/utils/teraconverter/teraconverter.cpp:212
212                     vcDriver(
```
